{
 "title": "EnviroSense",
 "tags": [ "temperature" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "Sensor ID",
    "query": "label_values(pressure_pascal,id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "expr": "(temperature_celsius{id=~\"$id\"} * 1.8) + 32",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "humidity_relative{id=~\"$id\"}",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    {
     "expr": "pressure_pascal{id=~\"$id\"} / 100",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "PIR Motion activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pir_motion_events{id=~\"$id\"} [2m])",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "WiFi signal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "RSSI" }
   ],
   "targets": [
    {
     "expr": "wifi_signal_rssi{id=~\"$id\"}",
     "legendFormat": "{{ id }}"
    }
   ]
  }
 ]
}